### ISSUE TITLE
make a html file with the js and css in it 

### ISSUE THREAD

**Issue by Project516** [dinguschan-owo/dingusproxy#11]

**Comment by Project516** [comment]
im tryed to do it but u update it so often (no problem) so when im done theres like 5 more changes

**Comment by dinguschan-owo** [comment]
Click the green button that says "Code" and hit download ZIP, then open in files, right click and hit "Extract All" then open the html file named "index.html" so that the CSS and JS will link and it will work. As for the update problem, this project is extremely janky rn, so I will continue to update this, but I can update less frquently for u :D. If you provide your email I can send u large releases to update to, but I can not push updates to you specifically due to his file being local and therefore unblockable. To continuously get updates just visit the website.

**Comment by dinguschan-owo** [comment]
I will update less often, with bigger updates, but to get updates real time visit the website
